### ISSUE TITLE
Two languages in the Oromo (orm) set

### ISSUE THREAD

**Issue by pascalhuszar** [afrisenti-semeval/afrisent-semeval-dataset#6]
Why are there files with two different languages for the Oromo set?
It seems that in dev.tsv the data points are in Tigrinya, while in test.tsv the data points are in Oromo. Also, I noticed that the same dev.tsv is inserted from Tigrinya (tir) into the Oromo set.

**Comment by shmuhammadd** [comment]
From HugginFace? https://huggingface.co/datasets/shmuhammad/AfriSenti-twitter-sentiment

**Comment by seyyaw** [comment]
Thank you @pascalhuszar You have noticed the issue.
We will fix it.

**Comment by shmuhammadd** [comment]
@pascalhuszar @seyyaw, we fixed the issue now. Thank you.

**Comment by seyyaw** [comment]
Thank you @shmuhammadd 
I see it is now corrected. Closing the issue.
